name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup npmrc
        run: |
          echo "@dev-wiki-kr:registry=https://npm.pkg.github.com"  >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> .npmrc

      - name: Export organization environment variables
        run: |
          npx @dev-wiki-kr/gha-tools@latest inject-env ./envs --env=production
          mv .env.service .env.production

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
            git pull origin main && docker compose down && docker compose up -d --build
